import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import PDFDocument from 'pdfkit';
import { env } from '../config/env.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pdfStoragePath = path.resolve(__dirname, '../../storage/pdfs');

function sanitizeFileName(value) {
  return String(value)
    .replace(/[^a-zA-Z0-9-_\. ]+/g, '-')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

async function ensurePdfStorage() {
  await fs.promises.mkdir(pdfStoragePath, { recursive: true });
}

function writePdf(doc, outputPath) {
  return new Promise((resolve, reject) => {
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);
    doc.end();
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

function getPdfFilePath(fileName) {
  return path.join(pdfStoragePath, fileName);
}

export function getPdfFileName(pdfUrl) {
  try {
    return path.basename(new URL(pdfUrl).pathname);
  } catch (error) {
    return path.basename(pdfUrl);
  }
}

export async function pdfExists(fileName) {
  try {
    await fs.promises.access(getPdfFilePath(fileName), fs.constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export async function generateInvoicePdf(invoice, customer) {
  await ensurePdfStorage();
  const fileName = `invoice-${sanitizeFileName(invoice._id.toString())}.pdf`;
  const outputPath = path.join(pdfStoragePath, fileName);
  const pdfUrl = `${env.PDF_BASE_URL}/${fileName}`;

  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  doc.fillColor('#0f172a').fontSize(22).text('NxtBiz', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor('#475569').text('Business Operations Automation', { align: 'center' });
  doc.moveDown(1.5);

  doc.fontSize(14).fillColor('#0f172a').text('Invoice', { underline: true });
  doc.moveDown(0.5);

  doc.fontSize(10).fillColor('#334155');
  doc.text(`Invoice ID: ${invoice._id}`);
  doc.text(`Status: ${invoice.status}`);
  doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`);
  if (customer?.name) {
    doc.text(`Customer: ${customer.name}`);
    if (customer.company) doc.text(`Company: ${customer.company}`);
    if (customer.email) doc.text(`Email: ${customer.email}`);
  }

  doc.moveDown(1);
  doc.fontSize(12).fillColor('#0f172a').text('Line Items', { underline: true });
  doc.moveDown(0.5);

  invoice.lineItems.forEach((item, index) => {
    doc.fontSize(10).fillColor('#334155');
    doc.text(`${index + 1}. ${item.description}`, { continued: true });
    doc.text(` - $${Number(item.amount).toFixed(2)}`, { align: 'right' });
  });

  doc.moveDown(1);
  doc.fontSize(12).fillColor('#0f172a').text(`Total Due: $${Number(invoice.amount).toFixed(2)}`, { align: 'right' });

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#64748b').text('Thank you for using NxtBiz for your operations workflow.', { align: 'center' });

  await writePdf(doc, outputPath);
  return pdfUrl;
}

export async function generateReportPdf(report) {
  await ensurePdfStorage();
  const fileName = `report-${sanitizeFileName(report._id.toString())}.pdf`;
  const outputPath = path.join(pdfStoragePath, fileName);
  const pdfUrl = `${env.PDF_BASE_URL}/${fileName}`;

  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  doc.fillColor('#0f172a').fontSize(22).text('NxtBiz', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor('#475569').text(report.type === 'executive' ? 'Executive Report' : 'Weekly Operations Report', { align: 'center' });
  doc.moveDown(1.5);

  doc.fontSize(14).fillColor('#0f172a').text(report.title, { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#334155').text(`Report ID: ${report._id}`);
  doc.text(`Generated: ${new Date(report.createdAt).toLocaleDateString()}`);
  doc.text(`Generated by: ${report.generatedBy || 'System'}`);

  doc.moveDown(1);
  doc.fontSize(12).fillColor('#0f172a').text('Summary', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#334155').text(report.summary || 'No summary provided.');

  doc.moveDown(1);
  doc.fontSize(12).fillColor('#0f172a').text('Key Metrics', { underline: true });
  doc.moveDown(0.5);

  Object.entries(report.metrics || {}).forEach(([label, value]) => {
    doc.fontSize(10).fillColor('#334155').text(`${label}: ${value}`);
  });

  if (report.recommendations?.length) {
    doc.moveDown(1);
    doc.fontSize(12).fillColor('#0f172a').text('Recommendations', { underline: true });
    doc.moveDown(0.5);
    report.recommendations.forEach((item, index) => {
      doc.fontSize(10).fillColor('#334155').text(`${index + 1}. ${item}`);
    });
  }

  doc.moveDown(2);
  doc.fontSize(9).fillColor('#64748b').text('Generated by NxtBiz analytics and automation intelligence.', { align: 'center' });

  await writePdf(doc, outputPath);
  return pdfUrl;
}
